GET http://localhost:4000/dishes/7

###
GET http://localhost:4000/dishes/7/9

###
POST http://localhost:4000/dishes/8
Content-Type: application/json

{
    "dishName": "Pollo alla cacciatora",
    "isAvailable": true,
    "price": 46.99,
    "description": "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    "calories": 500,
    "image": "https://www.foodandwine.com/thmb/20Fp26wbzSMgOtCdCZy0vpIK8Mo=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/garlic-butter-prime-rib-FT-RECIPE0621-fca73e5fa8e046b0b03982757db51628.jpg"
}

###
PUT http://localhost:4000/dishes/5
Content-Type: application/json

{
  "dishName": "Sapori di Napoli"
}

###
DELETE http://localhost:4000/dishes/10